services:
  app:
    build: .
    environment:
      SELENIUM_HOST: http://selenium:4444/
    volumes:
      - output:/var/www/html/output
      - temp:/var/www/html/temp
    depends_on:
      - selenium
    expose:
      - "80"
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    expose:
      - "4444"
    restart: unless-stopped

volumes:
  output:
  temp:
